# Generated by Django 5.1.1 on 2024-10-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_student_roll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app.rollnumber"
            ),
        ),
    ]
