# Generated by Django 5.1.1 on 2024-10-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_musician_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="num_stars",
        ),
        migrations.RemoveField(
            model_name="album",
            name="release_date",
        ),
    ]
