# Generated by Django 5.1.1 on 2024-10-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_album_num_stars_remove_album_release_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musician",
            name="instrument",
        ),
    ]
